version: '3'
services:
  nginx:
    build:
      context: ./frontend
      args:
      - api_server=http://api:80
    volumes:
    - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
    - "80:80"
    - "5984:5984"
    links:
    - rabbitmq
    - couchdb
    - api
    restart: always
  rabbitmq:
    image: rabbitmq
    ports:
    - "35197:35197"
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    volumes:
    - "./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    - "./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    restart: always
  couchdb:
    image: couchdb
    volumes:
    - "./data/couchdb/:/opt/couchdb/data"
    env_file: config/config.env
    restart: always
  postgres:
    image: postgres
    volumes:
    - "./data/postgres/:/var/lib/postgresql/data"
    env_file: config/config.env
    ports:
    - 5432:5432
    restart: always
  api:
    build:
      context: ./api
      args:
        - POSTGRES_PASSWORD
    volumes:
    - "./api/:/app"
    env_file: config/config.env
    environment:
    - MIX_ENV=dev
    restart: always
    ports:
    # Expose our API server on localhost:888, so our local dev frontend can use it
    - 888:80
    depends_on:
    - rabbitmq
    - couchdb
    - postgres
